server {
    listen 80;

    # Disable absolute redirects to prevent Nginx from inserting 'localhost' into redirects
    absolute_redirect off;

    # The directory where the frontend build files are stored inside the container.
    root /usr/share/nginx/html;

    # Serve the frontend static files.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
